global using Microsoft.UI;
global using Microsoft.UI.Windowing;
global using Microsoft.UI.Xaml;
global using System;
global using WinRT.Interop;
global using AppWindow = Microsoft.UI.Windowing.AppWindow;
global using PasswordBox.Models;
global using CommunityToolkit.Mvvm.ComponentModel;
global using PasswordBox.View;
//global using Microsoft.UI.Xaml.Controls;
//global using System.Collections.ObjectModel;
